# VesselGraph / ogbl-BALBc1

## Data (OGB dataloader)

In [1]:
from source.ogb.linkproppred import *
import numpy as np

data = LinkPropPredDataset(name='ogbl-BALBc_no1_spatial_edge_attr')


In [15]:
#print(len(data))
whole_dataset = data[0]
#print(whole_dataset)

for key, value in whole_dataset.items() :
    print(key)
    print(value)

edge_index
[[      0       1       2 ... 3538494 3538494 3538494]
 [ 278560       3  249900 ... 3538486 3538490 3538492]]
edge_feat
[[182.464    167.946      4.0269     0.493999   1.08644 ]
 [  9.98625    6.7082     2.06331    0.315612   1.48866 ]
 [  2.48805    2.44949    4.82482    0.433435   1.01574 ]
 ...
 [  9.16001    9.04926    2.49044    0.45713    1.01224 ]
 [ 10.8936     9.40043    6.12633    0.310315   1.15884 ]
 [  3.18663    3.14469    2.7655     0.562911   1.01333 ]]
node_feat
[[2.93200e+03 3.47700e+03 0.00000e+00 1.00000e+00 1.00000e+00]
 [2.91600e+03 3.50900e+03 0.00000e+00 1.00000e+00 1.00000e+00]
 [2.92900e+03 3.51400e+03 0.00000e+00 1.00000e+00 1.00000e+00]
 ...
 [9.90000e+02 2.19200e+03 1.86500e+03 2.00000e+00 0.00000e+00]
 [9.57000e+02 2.19600e+03 1.86500e+03 3.00000e+00 0.00000e+00]
 [9.92667e+02 2.19100e+03 1.86633e+03 3.00000e+00 0.00000e+00]]
num_nodes
3538495


In [16]:
node_list = np.ones((1, whole_dataset['num_nodes']))
node_feats = whole_dataset['node_feat']
edge_list = np.ones((1, len(whole_dataset['edge_feat'])))
edge_feats = whole_dataset['edge_feat']
edge = whole_dataset['edge_index']

In [4]:
final_data = {
    "node_list": node_list,
    "node_feats": node_feats,
    "edge": edge,
    "edge_list": edge_list,
    "edge_feats": edge_feats
}

In [ ]:
np.savez_compressed('obgl-BALBc1.npz', **final_data)

## Task

In [5]:
split_edge = data.get_edge_split()
train = split_edge['train']
validation = split_edge['valid']
test = split_edge['test']

In [6]:
edge_ids = {}
for count, e in enumerate(edge[0]):
    edge_ids[(e, edge[1][count])] = count

In [17]:
train_pos = []
for elt in train['edge']:
    i = elt.numpy()
    train_pos.append([i[0], edge_ids[tuple(i)], i[1]])

In [29]:
task_data = {
    "train_pos": train_pos,
    "train_neg": train['edge_neg'].numpy(),
    "validation": validation['edge'].numpy(),
    "validation_neg": validation['edge_neg'].numpy(),
    "test": test['edge'].numpy(),
    "test_neg": test['edge_neg'].numpy()
}

In [ ]:
np.savez_compressed('ogbl-BALBc1_link_prediction.npz', **task_data)